version: "3"

networks:
  default:
    external:
      name: macula-cloud-network

services:
  # Canal Admin
  macula-cloud-canal-admin:
    image: canal/canal-admin:v1.1.4
    container_name: macula-cloud-canal-admin
    restart: always
    ports:
      - 8089:8089
    environment:
      - server.port=8089
      - canal.adminUser=admin
      - canal.adminPasswd=admin
    volumes:
      - ${CANAL_HOME}/logs/:/home/admin/canal-admin/logs

  # Canal Server
  macula-cloud-canal-server:
    image: canal/canal-server:v1.1.4
    container_name: macula-cloud-canal-server
    restart: always
    ports:
      - 11111:11111
    depends_on:
      - macula-cloud-canal-admin
    environment:
      - canal.auto.scan=false
      # instance settings
      - cana.destinations=example
      - canal.instance.master.address=macula-cloud-mysql:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.instance.detecting.enable=true
      - canal.instance.detecting.interval.time=3
      - canal.instance.detecting.retry.threshold=3
      - canal.instance.detecting.heartbeatHaEnable=true
      # admin settings
      - canal.admin.manager=macula-cloud-canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.register.auto=true
      # - canal.admin.register.cluster=default
      - canal.serverMode=tcp
    volumes:
      - ${CANAL_HOME}/logs/:/admin/canal-server/logs/
