version: "3"

networks:
  default:
    external:
      name: macula-cloud-network

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  macula-cloud-kong-database:
    image: postgres:9.6
    container_name: macula-cloud-kong-database
    restart: always
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - ${KONG_HOME}/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  macula-cloud-kong-migration:
    image: kong:latest
    container_name: macula-cloud-kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_PG_HOST=macula-cloud-kong-database
      - KONG_DATABASE=postgres
      - KONG_PG_PASSWORD=${DB_PWD}
    depends_on:
      - macula-cloud-kong-database
    links:
      - macula-cloud-kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  macula-cloud-kong:
    image: kong:latest
    container_name: macula-cloud-kong
    restart: always
    environment:
      - KONG_PG_HOST=macula-cloud-kong-database
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_PASSWORD=${DB_PWD}
      - KONG_PROXY_ACCESS_LOG=/kong/access.log
      - KONG_PROXY_ACCESS_LOG=/usr/local/kong/logs/proxy_access.log
      - KONG_ADMIN_ACCESS_LOG=/usr/local/kong/logs/admin_access.log
      - KONG_PROXY_ERROR_LOG=/usr/local/kong/logs/proxy_error.log
      - KONG_ADMIN_ERROR_LOG=/usr/local/kong/logs/admin_error.log
    depends_on:
      - macula-cloud-kong-migration
      - macula-cloud-kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://macula-cloud-kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ${KONG_HOME}/conf/kong.conf:/etc/kong/kong.conf
      - ${KONG_HOME}/logs:/usr/local/kong/logs